// All 63 U.S. National Parks. Coordinates are approximate park centroids.
export const REGIONS = [
  "Northeast",
  "Southeast",
  "Midwest",
  "Southwest",
  "Rocky Mountains",
  "Pacific West",
  "Alaska",
  "Hawaiʻi & Pacific",
  "Caribbean",
];

export const PARKS = [
  { id: "acadia", name: "Acadia", states: "ME", region: "Northeast", lat: 44.35, lon: -68.21, est: 1919, blurb: "Granite peaks and rocky shoreline on Maine's Mount Desert Island." },
  { id: "american-samoa", name: "American Samoa", states: "AS", region: "Hawaiʻi & Pacific", lat: -14.25, lon: -170.68, est: 1988, blurb: "Tropical rainforest, coral reefs and Samoan villages in the South Pacific." },
  { id: "arches", name: "Arches", states: "UT", region: "Southwest", lat: 38.68, lon: -109.57, est: 1971, blurb: "Over 2,000 natural sandstone arches in the high desert." },
  { id: "badlands", name: "Badlands", states: "SD", region: "Midwest", lat: 43.75, lon: -102.50, est: 1978, blurb: "Eroded buttes and pinnacles above one of the largest mixed-grass prairies." },
  { id: "big-bend", name: "Big Bend", states: "TX", region: "Southwest", lat: 29.25, lon: -103.25, est: 1944, blurb: "Chihuahuan Desert, the Chisos Mountains and the Rio Grande." },
  { id: "biscayne", name: "Biscayne", states: "FL", region: "Southeast", lat: 25.65, lon: -80.08, est: 1980, blurb: "A mostly underwater park of coral reefs, keys and mangroves." },
  { id: "black-canyon", name: "Black Canyon of the Gunnison", states: "CO", region: "Rocky Mountains", lat: 38.57, lon: -107.72, est: 1999, blurb: "Sheer, dark-walled canyon carved by the Gunnison River." },
  { id: "bryce-canyon", name: "Bryce Canyon", states: "UT", region: "Southwest", lat: 37.57, lon: -112.18, est: 1928, blurb: "Amphitheaters crowded with orange hoodoos at 8,000+ feet." },
  { id: "canyonlands", name: "Canyonlands", states: "UT", region: "Southwest", lat: 38.20, lon: -109.93, est: 1964, blurb: "Mesas and canyons cut by the Colorado and Green rivers." },
  { id: "capitol-reef", name: "Capitol Reef", states: "UT", region: "Southwest", lat: 38.20, lon: -111.17, est: 1971, blurb: "The Waterpocket Fold, a 100-mile wrinkle in the earth's crust." },
  { id: "carlsbad-caverns", name: "Carlsbad Caverns", states: "NM", region: "Southwest", lat: 32.17, lon: -104.44, est: 1930, blurb: "More than 119 limestone caves beneath the Guadalupe Mountains." },
  { id: "channel-islands", name: "Channel Islands", states: "CA", region: "Pacific West", lat: 34.01, lon: -119.42, est: 1980, blurb: "Five wild islands off the Southern California coast." },
  { id: "congaree", name: "Congaree", states: "SC", region: "Southeast", lat: 33.78, lon: -80.78, est: 2003, blurb: "The largest old-growth bottomland hardwood forest in the Southeast." },
  { id: "crater-lake", name: "Crater Lake", states: "OR", region: "Pacific West", lat: 42.94, lon: -122.10, est: 1902, blurb: "The deepest lake in the U.S., filling a collapsed volcano." },
  { id: "cuyahoga-valley", name: "Cuyahoga Valley", states: "OH", region: "Midwest", lat: 41.24, lon: -81.55, est: 2000, blurb: "Forests, waterfalls and farmland along the Cuyahoga River." },
  { id: "death-valley", name: "Death Valley", states: "CA, NV", region: "Pacific West", lat: 36.24, lon: -116.82, est: 1994, blurb: "The hottest, driest and lowest place in North America." },
  { id: "denali", name: "Denali", states: "AK", region: "Alaska", lat: 63.33, lon: -150.50, est: 1917, blurb: "Six million acres around North America's tallest peak." },
  { id: "dry-tortugas", name: "Dry Tortugas", states: "FL", region: "Southeast", lat: 24.63, lon: -82.87, est: 1992, blurb: "Remote islands, reefs and 19th-century Fort Jefferson." },
  { id: "everglades", name: "Everglades", states: "FL", region: "Southeast", lat: 25.32, lon: -80.93, est: 1947, blurb: "The largest subtropical wilderness in the United States." },
  { id: "gates-of-the-arctic", name: "Gates of the Arctic", states: "AK", region: "Alaska", lat: 67.78, lon: -153.30, est: 1980, blurb: "Roadless wilderness entirely north of the Arctic Circle." },
  { id: "gateway-arch", name: "Gateway Arch", states: "MO", region: "Midwest", lat: 38.63, lon: -90.19, est: 2018, blurb: "The 630-foot stainless steel arch on the St. Louis riverfront." },
  { id: "glacier", name: "Glacier", states: "MT", region: "Rocky Mountains", lat: 48.80, lon: -114.00, est: 1910, blurb: "Glacier-carved peaks and the Going-to-the-Sun Road." },
  { id: "glacier-bay", name: "Glacier Bay", states: "AK", region: "Alaska", lat: 58.50, lon: -137.00, est: 1980, blurb: "Tidewater glaciers, fjords and humpback whales." },
  { id: "grand-canyon", name: "Grand Canyon", states: "AZ", region: "Southwest", lat: 36.06, lon: -112.14, est: 1919, blurb: "A mile-deep gorge carved by the Colorado River." },
  { id: "grand-teton", name: "Grand Teton", states: "WY", region: "Rocky Mountains", lat: 43.73, lon: -110.80, est: 1929, blurb: "Jagged Teton Range rising over Jackson Hole." },
  { id: "great-basin", name: "Great Basin", states: "NV", region: "Southwest", lat: 38.98, lon: -114.30, est: 1986, blurb: "Wheeler Peak, Lehman Caves and ancient bristlecone pines." },
  { id: "great-sand-dunes", name: "Great Sand Dunes", states: "CO", region: "Rocky Mountains", lat: 37.73, lon: -105.51, est: 2004, blurb: "The tallest sand dunes in North America." },
  { id: "great-smoky-mountains", name: "Great Smoky Mountains", states: "NC, TN", region: "Southeast", lat: 35.68, lon: -83.53, est: 1934, blurb: "Mist-covered Appalachian ridges; the most visited national park." },
  { id: "guadalupe-mountains", name: "Guadalupe Mountains", states: "TX", region: "Southwest", lat: 31.92, lon: -104.87, est: 1972, blurb: "Texas's highest peak atop an ancient fossil reef." },
  { id: "haleakala", name: "Haleakalā", states: "HI", region: "Hawaiʻi & Pacific", lat: 20.72, lon: -156.17, est: 1916, blurb: "A dormant volcano summit above the clouds on Maui." },
  { id: "hawaii-volcanoes", name: "Hawaiʻi Volcanoes", states: "HI", region: "Hawaiʻi & Pacific", lat: 19.38, lon: -155.20, est: 1916, blurb: "Kīlauea and Mauna Loa, two of the world's most active volcanoes." },
  { id: "hot-springs", name: "Hot Springs", states: "AR", region: "Southeast", lat: 34.51, lon: -93.05, est: 1921, blurb: "Thermal springs and historic Bathhouse Row." },
  { id: "indiana-dunes", name: "Indiana Dunes", states: "IN", region: "Midwest", lat: 41.65, lon: -87.05, est: 2019, blurb: "Lake Michigan beaches, dunes, wetlands and prairie." },
  { id: "isle-royale", name: "Isle Royale", states: "MI", region: "Midwest", lat: 48.10, lon: -88.55, est: 1940, blurb: "A roadless island wilderness in Lake Superior, home to wolves and moose." },
  { id: "joshua-tree", name: "Joshua Tree", states: "CA", region: "Pacific West", lat: 33.79, lon: -115.90, est: 1994, blurb: "Where the Mojave and Colorado deserts meet." },
  { id: "katmai", name: "Katmai", states: "AK", region: "Alaska", lat: 58.50, lon: -155.00, est: 1980, blurb: "Brown bears fishing at Brooks Falls and the Valley of Ten Thousand Smokes." },
  { id: "kenai-fjords", name: "Kenai Fjords", states: "AK", region: "Alaska", lat: 59.92, lon: -149.65, est: 1980, blurb: "The Harding Icefield and its tidewater glaciers." },
  { id: "kings-canyon", name: "Kings Canyon", states: "CA", region: "Pacific West", lat: 36.80, lon: -118.55, est: 1940, blurb: "Deep glacial canyons and giant sequoia groves." },
  { id: "kobuk-valley", name: "Kobuk Valley", states: "AK", region: "Alaska", lat: 67.55, lon: -159.28, est: 1980, blurb: "Arctic sand dunes and the caribou migration." },
  { id: "lake-clark", name: "Lake Clark", states: "AK", region: "Alaska", lat: 60.97, lon: -153.42, est: 1980, blurb: "Volcanoes, glaciers and salmon-rich lakes." },
  { id: "lassen-volcanic", name: "Lassen Volcanic", states: "CA", region: "Pacific West", lat: 40.49, lon: -121.51, est: 1916, blurb: "Steaming fumaroles and all four types of volcano." },
  { id: "mammoth-cave", name: "Mammoth Cave", states: "KY", region: "Southeast", lat: 37.18, lon: -86.10, est: 1941, blurb: "The longest known cave system in the world." },
  { id: "mesa-verde", name: "Mesa Verde", states: "CO", region: "Rocky Mountains", lat: 37.18, lon: -108.49, est: 1906, blurb: "Ancestral Puebloan cliff dwellings." },
  { id: "mount-rainier", name: "Mount Rainier", states: "WA", region: "Pacific West", lat: 46.85, lon: -121.75, est: 1899, blurb: "A glaciated 14,410-foot volcano and wildflower meadows." },
  { id: "new-river-gorge", name: "New River Gorge", states: "WV", region: "Southeast", lat: 38.07, lon: -81.08, est: 2020, blurb: "Whitewater and climbing in a deep Appalachian gorge." },
  { id: "north-cascades", name: "North Cascades", states: "WA", region: "Pacific West", lat: 48.70, lon: -121.20, est: 1968, blurb: "More than 300 glaciers among rugged alpine peaks." },
  { id: "olympic", name: "Olympic", states: "WA", region: "Pacific West", lat: 47.97, lon: -123.50, est: 1938, blurb: "Temperate rainforest, glaciated peaks and wild coastline." },
  { id: "petrified-forest", name: "Petrified Forest", states: "AZ", region: "Southwest", lat: 35.07, lon: -109.78, est: 1962, blurb: "Fossilized logs and the Painted Desert." },
  { id: "pinnacles", name: "Pinnacles", states: "CA", region: "Pacific West", lat: 36.48, lon: -121.16, est: 2013, blurb: "Volcanic rock spires, talus caves and California condors." },
  { id: "redwood", name: "Redwood", states: "CA", region: "Pacific West", lat: 41.30, lon: -124.00, est: 1968, blurb: "The tallest trees on Earth along the northern California coast." },
  { id: "rocky-mountain", name: "Rocky Mountain", states: "CO", region: "Rocky Mountains", lat: 40.40, lon: -105.58, est: 1915, blurb: "Alpine tundra and Trail Ridge Road across the Continental Divide." },
  { id: "saguaro", name: "Saguaro", states: "AZ", region: "Southwest", lat: 32.25, lon: -110.50, est: 1994, blurb: "Forests of giant saguaro cacti around Tucson." },
  { id: "sequoia", name: "Sequoia", states: "CA", region: "Pacific West", lat: 36.43, lon: -118.68, est: 1890, blurb: "The General Sherman Tree and Mount Whitney's western slopes." },
  { id: "shenandoah", name: "Shenandoah", states: "VA", region: "Southeast", lat: 38.53, lon: -78.35, est: 1935, blurb: "Skyline Drive along the Blue Ridge Mountains." },
  { id: "theodore-roosevelt", name: "Theodore Roosevelt", states: "ND", region: "Midwest", lat: 46.97, lon: -103.45, est: 1978, blurb: "Painted badlands and bison along the Little Missouri River." },
  { id: "virgin-islands", name: "Virgin Islands", states: "VI", region: "Caribbean", lat: 18.33, lon: -64.73, est: 1956, blurb: "White-sand beaches and coral reefs on St. John." },
  { id: "voyageurs", name: "Voyageurs", states: "MN", region: "Midwest", lat: 48.50, lon: -92.88, est: 1975, blurb: "Interconnected lakes along the old fur-trade route." },
  { id: "white-sands", name: "White Sands", states: "NM", region: "Southwest", lat: 32.78, lon: -106.17, est: 2019, blurb: "The world's largest gypsum dunefield." },
  { id: "wind-cave", name: "Wind Cave", states: "SD", region: "Midwest", lat: 43.57, lon: -103.48, est: 1903, blurb: "Boxwork caves beneath bison-grazed prairie." },
  { id: "wrangell-st-elias", name: "Wrangell–St. Elias", states: "AK", region: "Alaska", lat: 61.00, lon: -142.00, est: 1980, blurb: "The largest national park, at 13.2 million acres." },
  { id: "yellowstone", name: "Yellowstone", states: "WY, MT, ID", region: "Rocky Mountains", lat: 44.60, lon: -110.50, est: 1872, blurb: "The first national park: geysers, hot springs and wildlife." },
  { id: "yosemite", name: "Yosemite", states: "CA", region: "Pacific West", lat: 37.83, lon: -119.50, est: 1890, blurb: "Granite cliffs, waterfalls and giant sequoias." },
  { id: "zion", name: "Zion", states: "UT", region: "Southwest", lat: 37.30, lon: -113.05, est: 1919, blurb: "Towering sandstone cliffs and the Narrows of the Virgin River." },
];

export const STATE_NAMES = {
  AK: "Alaska", AR: "Arkansas", AS: "American Samoa", AZ: "Arizona", CA: "California",
  CO: "Colorado", FL: "Florida", HI: "Hawaii Hawaiʻi", ID: "Idaho", IN: "Indiana",
  KY: "Kentucky", ME: "Maine", MI: "Michigan", MN: "Minnesota", MO: "Missouri",
  MT: "Montana", NC: "North Carolina", ND: "North Dakota", NM: "New Mexico", NV: "Nevada",
  OH: "Ohio", OR: "Oregon", SC: "South Carolina", SD: "South Dakota", TN: "Tennessee",
  TX: "Texas", UT: "Utah", VA: "Virginia", VI: "U.S. Virgin Islands", WA: "Washington",
  WV: "West Virginia", WY: "Wyoming",
};
